# -*- coding: utf-8 -*-
"""Last updated 5-2-2025 Super Store-Store Sales Analysis semifinal  last update.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMo7-F6MHmpiToF9G1yzwx-g3K9UHf9T

##  ***importing***data**
"""

import pandas as pd

# Try reading the file with 'latin-1' encoding
file = pd.read_csv("Superstore Sales Dataset.csv", encoding='latin-1')
# If 'latin-1' doesn't work, try 'cp1252'
# file = pd.read_csv("Superstore Sales Dataset.csv", encoding='cp1252')
file

"""##** EXPLORING DATA**"""

file.head()

file.tail()

file.shape

file.dtypes

file.info()

file.columns

# Assuming 'file' contains your original DataFrame

# Select categorical features (replace with your actual categorical columns)
# The column name was changed from 'Ship Mode' to 'Ship_Mode'
#file_cat = file[['Ship_Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category']]
#The above line had the error, It has been corrected to the below
file_cat = file[['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Region', 'Category', 'Sub-Category']] # Replaced 'Ship_Mode' with 'Ship Mode'

# Now you can iterate through the columns of 'file_cat'
for feature in file_cat.columns:
    print(feature,':',file[feature].nunique())

"""## TASK1-**cleaning**

## Check for missing values
"""

file.isnull().sum()

file.isnull().sum().sum()

file.duplicated().sum()

"""## Convert 'Order Date' and 'Ship Date' to datetime"""

file['Order Date'] = pd.to_datetime(file['Order Date'], format='%m/%d/%Y') # Changed format to '%m/%d/%Y'
file['Ship Date'] = pd.to_datetime(file['Ship Date'], format='%m/%d/%Y') # Changed format to '%m/%d/%Y'

file.info()

# Describe salesto check for anomalies
sales_summary = file[['Sales','Quantity','Discount','Profit']].describe() # Changed tuple to list for column selection
sales_summary

"""## التعامل مع القيم الشاذة (Outliers)

"""

import seaborn as sns
sns.boxplot(data=file[['Sales','Quantity','Discount','Profit']])

"""##  استخدام التقسيم أو التجميع (Binning or Bucketing)


"""

bins = [0, 500, 1000, 5000, 10000, 20000]
labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']
file['Sales_Category'] = pd.cut(file['Sales'], bins=bins, labels=labels) # Changed 'data' to 'file' to refer to the correct DataFrame

file.info()  #added sale catagory to deal with outliers

file.isnull().sum()

import pandas as pd

# Assuming 'file' contains your original DataFrame

# Define bins and labels for 'Sales_Category'
bins = [0, 500, 1000, 5000, 10000, 20000]
labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']

# Create the 'Sales_Category' column
file['Sales_Category'] = pd.cut(file['Sales'], bins=bins, labels=labels)

# Now you can access the 'Sales_Category' column
most_frequent = file['Sales_Category'].mode()[0]     #استبدال القيم المفقودة بالقيمة الأكثر تكرارًا
file['Sales_Category'].fillna(most_frequent, inplace=True)

file.isnull().sum()

file.rename(columns={'Row ID':'Identity_Key','Order Date': 'order_date', 'Postal Code': 'postal_code','Ship Date':'Ship_Date','Ship Mode':'Ship_Mode'}, inplace=True)
#إعادة تسمية الأعمدة

file.columns

# إضافة عمود الشهر
file['Month'] = file['order_date'].dt.month # Changed 'Order Date' to 'order_date'

# إضافة عمود السنة
file['Year'] = file['order_date'].dt.year # Changed 'Order Date' to 'order_date'

# عرض البيانات للتحقق
print(file[['order_date', 'Month', 'Year']].head()) # Changed 'Order Date' to 'order_date'

# إضافة عمود جديد للربع السنوي باستخدام أسماء الأرباع
file['Quarter'] = file['order_date'].dt.quarter.map({1: 'Q1', 2: 'Q2', 3: 'Q3', 4: 'Q4'})

# عرض أول خمس صفوف للتأكد
print(file[['order_date', 'Month', 'Year','Quarter']].head()) # Changed 'Order Date' to 'order_date' to match the column name

# إضافة عمود نسبة الربح إلى المبيعات (Profit Margin)
file['Profit_Margin'] = (file['Profit'] / file['Sales']) * 100

# إضافة عمود متوسط الخصم لكل طلب
file['Average_Discount_Per_Order'] = file.groupby('Order ID')['Discount'].transform('mean')

# إضافة عمود إجمالي الكمية المباعة لكل طلب
file['Total_Quantity_Per_Order'] = file.groupby('Order ID')['Quantity'].transform('sum')

# حساب نسبة الخصم إلى المبيعات (Discount Percentage)
file['Discount_Percentage'] = (file['Discount'] / file['Sales']) * 100

# إضافة عمود نسبة الربح إلى إجمالي المبيعات (Profit Percentage)
file['Profit_Percentage'] = (file['Profit'] / file['Sales']) * 100

# عرض بعض العينات للتحقق من القيم
print(file[['Sales', 'Profit', 'Discount', 'Profit_Margin', 'Discount_Percentage',
            'Average_Discount_Per_Order', 'Total_Quantity_Per_Order', 'Profit_Percentage']].head())

# توحيد العملات
conversion_rate = 1  # Define the conversion rate here, e.g., 1 for no conversion
file['Sales'] = file['Sales'] * conversion_rate

# حساب الفرق بين التواريخ وإضافته كعمود جديد
file['Shipping Duration'] = (file['Ship_Date'] - file['order_date']).dt.days

file.columns

columns_order = [
    'Identity_Key','Order ID', 'order_date', 'Ship_Date', 'Shipping Duration', 'Ship_Mode',
    'Customer ID', 'Customer Name', 'Segment', 'postal_code', 'Country', 'City', 'State',
    'Region', 'Product ID', 'Product Name', 'Category', 'Sub-Category',
    'Sales', 'Quantity', 'Discount', 'Profit', 'Profit_Margin', 'Discount_Percentage','Profit_Percentage',
    'Average_Discount_Per_Order', 'Total_Quantity_Per_Order', 'Sales_Category', 'Month', 'Year', 'Quarter',
]

# إعادة ترتيب الأعمدة
file = file[columns_order]
#عادة ترتيب الأعمدة لتحسين عرض البيانات

file.columns

file.info()

import os

# Create the directory if it doesn't exist
os.makedirs('/mnt/data', exist_ok=True)

# Now you can save the file
file.to_csv('/mnt/data/Superstore_Sales_with_Quarters.csv', index=False)

from google.colab import files
# Change the filename to match the saved filename
files.download('/mnt/data/Superstore_Sales_with_Quarters.csv')

"""## **modeling**

## CREATING PRIMARY KEYS FOR TABLES
"""

file['LOCATION KEY'] = file['postal_code'].astype(str) + "_" + file['State']
file['PRODUCT KEY'] = file['Product ID'].astype(str) + "_" + file['Product Name']

file.to_csv('Superstore_Sales_with_Keys.csv', index=False) # Assuming you want to save it as "Superstore_Sales_with_Keys.csv"
from google.colab import files

files.download('Superstore_Sales_with_Keys.csv')

file.info()

# إنشاء جداول فرعية

# Orders Table
orders_table = file[[
   'Identity_Key', 'Order ID', 'order_date', 'Ship_Date', 'Shipping Duration', 'Ship_Mode',
    'Month', 'Year', 'Quarter', 'Quantity', 'Sales', 'Profit', 'Discount',
    'Sales_Category', 'Profit_Margin', 'Discount_Percentage', 'Profit_Percentage',
    'Average_Discount_Per_Order', 'Total_Quantity_Per_Order', 'Customer ID','postal_code','Region','City', # Removed the leading space before 'City'
    'LOCATION KEY', 'Product ID','Product Name','PRODUCT KEY'
]].drop_duplicates()

# Customers Table
customers_table = file[[
    'Customer ID', 'Customer Name', 'Segment'
]].drop_duplicates()

# Products Table
products_table = file[[
    'PRODUCT KEY', 'Product ID', 'Product Name', 'Category', 'Sub-Category'
]].drop_duplicates()

# Location Table
location_table = file[[  # Changed to lowercase 'location_table' for consistency
    'LOCATION KEY', 'postal_code', 'Region', 'Country', 'State', 'City'
]].drop_duplicates()

# حفظ الجداول كملفات CSV
orders_table.to_csv('orders_table.csv', index=False)
customers_table.to_csv('customers_table.csv', index=False)
products_table.to_csv('products_table.csv', index=False)
location_table.to_csv('location_table.csv', index=False)  # Changed LOCATION_table to location_tableع

from google.colab import files

# Download each file
files.download('orders_table.csv')
files.download('customers_table.csv')
files.download('products_table.csv')
files.download('location_table.csv')  # Changed 'LOCATION_table.csv' to 'location_table.csv'

print("تم تنزيل الملفات!")

"""## **TASK2-ANALYSIS OF DATA**

## خطوات دمج **الجداول** للتوضيح فقط
✅## ## تحديد المفاتيح الأساسية والعلاقات:

## orders: مفتاحه الأساسي هو Order ID.
## products: مفتاحه الأساسي هو Product ID.
## customers: مفتاحه الأساسي هو Customer ID.
## regions: مفتاحه الأساسي هو postal_code.

##import pandas as pd

# دمج جدول الطلبات مع العملاء
orders_customers = pd.merge(orders_table, customers_table, on='Customer ID', how='left')

# دمج الناتج مع جدول المنتجات
orders_customers_products = pd.merge(orders_customers, products_table, on='Product ID', how='left')

# دمج الناتج مع جدول الموقع
final_data = pd.merge(orders_customers_products, regions_table, on='postal_code', how='left')

# عرض بعض الصفوف للتأكد
print(final_data.head())

## **2-1 Describtive Overall Finacial Analysis**
"""

#إجماليات الأداء المالي
total_sales = orders_table['Sales'].sum()
total_profit = orders_table['Profit'].sum()
total_discount = orders_table['Discount'].sum()
overall_profit_margin = (total_profit / total_sales) * 100
sales_percentage = (total_sales / total_sales) * 100  # Always 100%
profit_percentage = (total_profit / total_sales) * 100
discount_percentage = (total_discount / total_sales) * 100

print("===== إجماليات الأداء المالي =====")
print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Total Discount: ${total_discount:,.2f}")
print(f"Overall Profit Margin: {overall_profit_margin:.2f}%\n")
print(f"Sales Percentage: {sales_percentage:.2f}%")
print(f"Profit Percentage: {profit_percentage:.2f}%")
print(f"Discount Percentage: {discount_percentage:.2f}%\n")

import pandas as pd

# قراءة جدول الطلبات
# Corrected file path to 'orders_table.csv'
orders_table = pd.read_csv('orders_table.csv')  # تأكدي من المسار

# تحديد الأعمدة ذات العلاقة بالتحليل المالي
columns_to_analyze = ['Quantity','Sales', 'Profit', 'Discount', 'Profit_Percentage', 'Profit_Margin',
                      'Discount_Percentage','Average_Discount_Per_Order',
                      'Total_Quantity_Per_Order']  #Fixed typos and extra spaces, separated concatenated columns


# حساب وصف إحصائي مفصل
financial_analysis = orders_table[columns_to_analyze].describe()

# تلوين القيم السالبة باللون الأحمر
def highlight_negative(s):
    '''
    تلوين القيم السالبة باللون الأحمر
    '''
    is_negative = s < 0  # تحديد القيم السالبة فقط
    return ['background-color: red' if v else '' for v in is_negative]  # تطبيق التنسيق

# تطبيق التلوين على الجدول
styled_financial_analysis = financial_analysis.style.apply(highlight_negative)

# عرض النتائج الملونة
display(styled_financial_analysis)

import seaborn as sns
sns.histplot(x=orders_table['Sales'], bins=30, kde=True)

import seaborn as sns
sns.histplot(x=orders_table['Quantity'], bins=30, kde=True)

import seaborn as sns
sns.histplot(x=orders_table['Discount'], bins=30, kde=True)

import seaborn as sns
sns.histplot(x=orders_table['Profit'], bins=30, kde=True)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# قراءة جدول الطلبات
# Corrected file path to 'orders_table.csv'
orders_table = pd.read_csv('orders_table.csv')  # تأكد من صحة مسار الملف

# رسم تحليل العلاقة بين الخصومات والأرباح
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Discount', y='Profit', data=orders_table, color='blue')
plt.title('Discount vs. Profit', fontsize=14)
plt.xlabel('Discount', fontsize=12)
plt.ylabel('Profit', fontsize=12)
plt.grid(True)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'orders_table' was created and saved as 'orders_table.csv' earlier
orders_table = pd.read_csv('orders_table.csv')  # Read from the saved CSV file

# تحديد الأعمدة المالية للتحليل
financial_columns = ['Sales', 'Profit', 'Quantity', 'Discount']

# إنشاء مصفوفة الترابط
correlation_matrix = orders_table[financial_columns].corr()

# رسم Heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix for Financial Metrics')
plt.show()

"""## **(Marketing Performance Analysis)**

"""

#bins = [0, 500, 1000, 5000, 10000, 20000]
#labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']
#إجمالي المبيعات والأرباح حسب الفئة
category_analysis = orders_table.groupby('Sales_Category').agg({ # Changed 'Sales-Category' to 'Sales_Category'
    'Sales': 'sum',
    'Profit': 'sum',
    'Discount': 'mean'  # Calculate average discount
}).reset_index()

print(category_analysis)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Assuming you have already calculated 'category_analysis' with the corrected column name
# And you want to include 'Discount' in the visualization

# Calculate average discount for each sales category
category_analysis = orders_table.groupby('Sales_Category').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Discount': 'mean'  # Calculate average discount
}).reset_index()

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the combo chart
fig, ax1 = plt.subplots(figsize=(12, 6))  # Increased figure size for better readability

# Bar chart for Total Sales and Total Profit
bar_width = 0.35  # Adjust bar width for better spacing
x_pos = np.arange(len(category_analysis['Sales_Category']))

ax1.bar(x_pos, category_analysis['Sales'], width=bar_width, label='Total Sales', color='skyblue')
ax1.bar(x_pos + bar_width, category_analysis['Profit'], width=bar_width, label='Total Profit', color='lightcoral')

# Customize primary y-axis (for Sales and Profit)
ax1.set_ylabel('Amount', fontsize=14)
ax1.set_xlabel('Sales Category', fontsize=14)
ax1.set_title('Sales, Profit, and Discount by Sales Category', fontsize=16, fontweight='bold')
ax1.set_xticks(x_pos + bar_width / 2)  # Center x-axis ticks between bars
ax1.set_xticklabels(category_analysis['Sales_Category'], rotation=45, ha='right', fontsize=12)
ax1.legend(loc='upper left', fontsize=12)

# Secondary y-axis for Average Discount (line chart)
ax2 = ax1.twinx()
ax2.plot(x_pos + bar_width / 2, category_analysis['Discount'], marker='o', color='darkgreen', label='Average Discount')  # Added line for discount
ax2.set_ylabel('Average Discount', fontsize=14)
ax2.legend(loc='upper right', fontsize=12)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

# إنشاء مجموعة لتجميع الخصومات مع متوسط الأرباح
discount_profit_analysis = orders_table.groupby('Discount')['Profit'].mean().reset_index()

# عرض البيانات
print(discount_profit_analysis)

# فلترة الخصومات التي تؤدي إلى أرباح سلبية
loss_discounts = discount_profit_analysis[discount_profit_analysis['Profit'] < 0]
print(loss_discounts)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))

# رسم الخط مع تحسينات
sns.lineplot(data=discount_profit_analysis, x='Discount', y='Profit', marker='o', color='blue', linestyle='--', linewidth=2)

# إبراز نقاط حرجة (مثال)
plt.axvline(x=0.2, color='gray', linestyle='--') # خط رأسي عند خصم 20%
plt.axhline(y=0, color='red', linestyle='-') # خط أفقي عند ربح 0

# إضافة تسميات لنقاط (مثال)
for x, y in zip(discount_profit_analysis['Discount'], discount_profit_analysis['Profit']):
    if x in [0.1, 0.2, 0.3]:  # نقاط محددة
        plt.text(x, y, f'({x:.1f}, {y:.2f})', ha='center', va='bottom', fontsize=10)

# تحسينات أخرى
plt.title('Effect of Discount on Profit', fontsize=16, fontweight='bold')
plt.xlabel('Discount (%)', fontsize=12)
plt.ylabel('Average Profit', fontsize=12)
plt.grid(True, linestyle='-', alpha=0.5) # شبكة أكثر وضوحًا
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Discount', y='Sales', hue='Profit', data=orders_table, palette='viridis', s=50)
plt.title('Relationship between Discount, Sales, and Profit')
plt.xlabel('Discount (%)')
plt.ylabel('Sales')
plt.show()

"""## **  بتحليل الاتجاهات الزمنية (Time Trends)**

## **overall analysis for Time**
"""

##لرسم سيوضح أي الشهور تتفوق في الأداء مقارنة بباقي الشهور.
##ستظهر الأعمدة البرتقالية (نسبة التغير) مدى ثبات أو تذبذب المبيعات بين الشهور.

import matplotlib.pyplot as plt
import pandas as pd

# Assuming 'orders_table' contains your data
# Create the 'sales_trend' DataFrame by grouping and aggregating sales by year and month
sales_trend = orders_table.groupby(['Year', 'Month'])['Sales'].sum().reset_index()
sales_trend['Year-Month'] = sales_trend['Year'].astype(str) + '-' + sales_trend['Month'].astype(str).str.zfill(2)  # Create 'Year-Month' column

# Now you can proceed with the rest of your code:
# تحويل 'Year-Month' إلى نوع بيانات datetime
sales_trend['Year-Month'] = pd.to_datetime(sales_trend['Year-Month'], format='%Y-%m')

# تقسيم البيانات حسب السنة
for year in sales_trend['Year'].unique():
    yearly_data = sales_trend[sales_trend['Year'] == year]
    plt.plot(yearly_data['Year-Month'], yearly_data['Sales'], label=year)

# تعيين تنسيق المحور X لعرض الشهور فقط
plt.gca().xaxis.set_major_formatter(plt.matplotlib.dates.DateFormatter('%b'))
plt.gcf().autofmt_xdate()  # تحسين دوران التسميات

plt.legend()
plt.show()

"""## **over years**"""

# تجميع البيانات حسب السنوات
yearly_analysis = orders_table.groupby('Year').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Discount': 'mean'
}).reset_index()

# عرض البيانات المجمعة
print(yearly_analysis)

plt.figure(figsize=(14, 8))

# رسم المبيعات
sns.lineplot(data=yearly_analysis, x='Year', y='Sales', label='Sales', marker='o', color='blue')

# رسم الأرباح
sns.lineplot(data=yearly_analysis, x='Year', y='Profit', label='Profit', marker='o', color='green')

# رسم الخصومات
sns.lineplot(data=yearly_analysis, x='Year', y='Discount', label='Discount', marker='o', color='red')

# تحسينات الرسم
plt.title('Sales, Profit, and Discount Trends Over Years', fontsize=16)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Value', fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# إضافة أعمدة جديدة للنسب المئوية
yearly_analysis['Profit_to_Sales (%)'] = (yearly_analysis['Profit'] / yearly_analysis['Sales']) * 100
yearly_analysis['Discount_to_Sales (%)'] = yearly_analysis['Discount'] * 100

# عرض البيانات مع النسب
print(yearly_analysis)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

# رسم نسبة الأرباح إلى المبيعات مع تحسينات
sns.lineplot(data=yearly_analysis, x='Year', y='Profit_to_Sales (%)',
             label='Profit to Sales (%)', marker='o', color='#008080', linewidth=2.5)  # Teal color, thicker line

# رسم نسبة الخصومات إلى المبيعات مع تحسينات
sns.lineplot(data=yearly_analysis, x='Year', y='Discount_to_Sales (%)',
             label='Discount to Sales (%)', marker='s', color='#FFA07A', linewidth=2.5, linestyle='--')  # Light Salmon, thicker dashed line

# إضافة تسميات لنقاط البيانات
for x, y in zip(yearly_analysis['Year'], yearly_analysis['Profit_to_Sales (%)']):
    plt.text(x, y, f'{y:.2f}%', ha='center', va='bottom', fontsize=10)  # Profit labels

for x, y in zip(yearly_analysis['Year'], yearly_analysis['Discount_to_Sales (%)']):
    plt.text(x, y, f'{y:.2f}%', ha='center', va='top', fontsize=10)  # Discount labels


# تحسينات الرسم
plt.title('Profit and Discount Percentage Relative to Sales (Over Years)', fontsize=16, fontweight='bold')
plt.xlabel('Year', fontsize=14)
plt.ylabel('Percentage (%)', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)  # Lighter grid
sns.despine()  # Remove top and right spines
plt.tight_layout()
plt.show()

"""## **Over Quarter**"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# تجميع البيانات حسب الربع
quarterly_analysis = orders_table.groupby('Quarter').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Discount': 'mean'
}).reset_index()

# رسم العلاقة بين الأرباح والمبيعات لكل ربع مع تحسينات
plt.figure(figsize=(12, 6))

# Use a clustered bar chart for better comparison
width = 0.35  # Width of each bar
x = np.arange(len(quarterly_analysis['Quarter']))

# Plot Sales and Profit side-by-side
plt.bar(x - width/2, quarterly_analysis['Sales'], width, label='Sales', color='skyblue')
plt.bar(x + width/2, quarterly_analysis['Profit'], width, label='Profit', color='lightcoral')

# Add data labels for better clarity
for i, v in enumerate(quarterly_analysis['Sales']):
    plt.text(i - width/2, v + 500, str(int(v)), ha='center', color='black', fontsize=10)  # Sales labels
for i, v in enumerate(quarterly_analysis['Profit']):
    plt.text(i + width/2, v + 500, str(int(v)), ha='center', color='black', fontsize=10)  # Profit labels

# Customize the plot
plt.title('Quarterly Sales and Profit Analysis', fontsize=16, fontweight='bold')
plt.xlabel('Quarter', fontsize=14)
plt.ylabel('Value', fontsize=14)
plt.xticks(x, quarterly_analysis['Quarter'], fontsize=12)
plt.yticks(fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)  # Lighter grid
sns.despine()  # Remove top and right spines for a cleaner look
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'quarterly_analysis' is already calculated

# رسم تأثير الخصومات على الأرباح لكل ربع مع تحسينات
plt.figure(figsize=(12, 6))

# Use a more distinct color palette
sns.scatterplot(
    data=quarterly_analysis,
    x='Discount',
    y='Profit',
    hue='Quarter',
    palette='Set1',  # Use a colorblind-friendly palette
    s=100,
    alpha=0.7,  # Add transparency for better readability
    edgecolor='black',  # Add edge color to the markers
    linewidth=1.2,  # Adjust linewidth for better visibility
)

# Customize the plot
plt.title('Discount vs Profit per Quarter', fontsize=16, fontweight='bold')
plt.xlabel('Average Discount', fontsize=14)
plt.ylabel('Total Profit', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.7)  # Lighter grid
sns.despine()  # Remove top and right spines for a cleaner look
plt.legend(fontsize=12, title='Quarter', title_fontsize=12)  # Customize legend

plt.tight_layout()
plt.show()

sales_by_quarter = orders_table.groupby('Quarter')['Sales'].sum()
print(sales_by_quarter)

"""## **over Month**"""

# حساب إجمالي المبيعات لكل شهر عبر جميع السنوات
monthly_avg_sales = orders_table.groupby('Month')['Sales'].mean().reset_index()

# ترتيب الشهور
monthly_avg_sales = monthly_avg_sales.sort_values('Month')

# عرض البيانات
print(monthly_avg_sales)

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming you have already calculated 'monthly_avg_sales'

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the bar plot
plt.figure(figsize=(12, 6))
ax = sns.barplot(x='Month', y='Sales', data=monthly_avg_sales, palette='viridis')

# Customize the plot
plt.title('Average Monthly Sales Across All Years', fontsize=16, fontweight='bold')
plt.xlabel('Month', fontsize=14)
plt.ylabel('Average Sales', fontsize=14)
plt.xticks(rotation=45, ha='right', fontsize=12)

# Add labels to the bars
for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center', xytext=(0, 10), textcoords='offset points', fontsize=10)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

# إضافة عمود لنسبة التغير
monthly_avg_sales['Percentage Change'] = monthly_avg_sales['Sales'].pct_change() * 100

# عرض البيانات
print(monthly_avg_sales)

# تجميع البيانات حسب الشهر
monthly_analysis = orders_table.groupby('Month').agg({'Profit': 'sum', 'Discount': 'mean'}).reset_index()

# عرض البيانات
print(monthly_analysis)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 7))

# خط المبيعات الشهرية
plt.plot(monthly_avg_sales['Month'], monthly_avg_sales['Sales'], marker='o', label='Monthly Avg Sales', color='darkblue', linewidth=2)

# إضافة تسميات لقيم المبيعات
for x, y in zip(monthly_avg_sales['Month'], monthly_avg_sales['Sales']):
    plt.text(x, y, f'{y:.2f}', ha='center', va='bottom', fontsize=10)

# نسبة التغيير
plt.bar(monthly_avg_sales['Month'], monthly_avg_sales['Percentage Change'], alpha=0.5, color='lightcoral', label='Percentage Change')

# تحسينات التنسيق
plt.title('Monthly Sales Trends and Percentage Change', fontsize=18, fontweight='bold')
plt.xlabel('Month', fontsize=14)
plt.ylabel('Sales / Percentage Change', fontsize=14)
plt.xticks(monthly_avg_sales['Month'], rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
sns.despine() # Remove the top and right spines
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Calculate average discount for each month
monthly_analysis = orders_table.groupby('Month').agg({
    'Profit': 'sum',
    'Discount': 'mean'  # Calculate average discount
}).reset_index()

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the combo chart
fig, ax1 = plt.subplots(figsize=(12, 6))  # Increased figure size for better readability

# Bar chart for Discount
bar_width = 0.35  # Adjust bar width for better spacing
x_pos = np.arange(len(monthly_analysis['Month']))
ax1.bar(x_pos, monthly_analysis['Discount'], width=bar_width, label='Discount', color='red')

# Customize primary y-axis (for Discount)
ax1.set_ylabel('Average Discount', fontsize=14)
ax1.set_xlabel('Month', fontsize=14)
ax1.set_title('Profit and Discount Trends Over Months', fontsize=16, fontweight='bold')
ax1.set_xticks(x_pos)  # Set x-axis ticks for each month
ax1.set_xticklabels(monthly_analysis['Month'], rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels

# Secondary y-axis for Profit (line chart)
ax2 = ax1.twinx()
ax2.plot(x_pos, monthly_analysis['Profit'], marker='o', color='green', label='Profit')  # Plot profit line
ax2.set_ylabel('Total Profit', fontsize=14)

# Add legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left', fontsize=12)  # Combine legends

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

#  تجميع البيانات وحساب المبيعات اليومية لكل شهر, discount, profit
# Convert 'order_date' to datetime if it's not already
orders_table['order_date'] = pd.to_datetime(orders_table['order_date'])
daily_sales_by_month = orders_table.groupby(['Month', orders_table['order_date'].dt.day]).agg(
    {'Sales': 'sum', 'Discount': 'mean', 'Profit': 'sum'}  # Include Discount and Profit
).reset_index()

#  إعادة تسمية الأعمدة
daily_sales_by_month.columns = ['Month', 'Day', 'Sales', 'Average Discount', 'Total Profit']

#  إيجاد اليوم ذو أعلى مبيعات لكل شهر
top_sales_days = daily_sales_by_month.loc[daily_sales_by_month.groupby('Month')['Sales'].idxmax()]

# 6. عرض النتائج مع تلوين profit سالب باللون الأحمر
def highlight_negative_profit(s):
    '''
    تلوين القيم السالبة في عمود 'Total Profit' باللون الأحمر
    '''
    is_negative = s < 0
    return ['color: red' if v else '' for v in is_negative]

styled_top_sales_days = top_sales_days.style.apply(highlight_negative_profit, axis=0, subset=['Total Profit'])
display(styled_top_sales_days)  # Use display for styled output in Jupyter Notebook

"""## focus on march

"""

average_discount_march = orders_table[orders_table['Month'] == 3]['Discount'].mean()
average_discount_other_months = orders_table[orders_table['Month'] != 3]['Discount'].mean()
print(average_discount_march)
print(average_discount_other_months)

daily_sales_march = orders_table[orders_table['Month'] == 3].groupby('order_date')['Sales'].sum() # Changed 'Order Date' to 'order_date'
print(daily_sales_march)

# 3. تجميع البيانات وحساب المبيعات اليومية لكل شهر, discount, profit
# Convert 'order_date' to datetime if it's not already
orders_table['order_date'] = pd.to_datetime(orders_table['order_date'])

# Filter data for March (Month 3)
march_data = orders_table[orders_table['Month'] == 3]

daily_sales_march = march_data.groupby(march_data['order_date'].dt.day).agg(
    {'Sales': 'sum', 'Discount': 'mean', 'Profit': 'sum'}  # Include Discount and Profit
).reset_index()


# 4. إعادة تسمية الأعمدة
daily_sales_march.columns = ['Day', 'Sales', 'Average Discount', 'Total Profit']

# 5. إيجاد اليوم ذو أعلى مبيعات لكل شهر
top_sales_days_march = daily_sales_march.loc[daily_sales_march['Sales'].idxmax()] # Find the day with maximum sales

# Convert the Series to a DataFrame with a single row before styling:
top_sales_days_march = top_sales_days_march.to_frame().T  # Transpose to have columns

# 6. عرض النتائج مع تلوين profit سالب باللون الأحمر
def highlight_negative_profit(s):
    '''
    تلوين القيم السالبة في عمود 'Total Profit' باللون الأحمر
    '''
    is_negative = s < 0
    return ['color: red' if v else '' for v in is_negative]

styled_top_sales_days_march = top_sales_days_march.style.apply(highlight_negative_profit, axis=0, subset=['Total Profit']) # Convert to DataFrame for styling
display(styled_top_sales_days_march)  # Use display for styled output in Jupyter Notebook

"""## **تحليل جدول العملاء (customers_table)**


"""

# 1. Total number of customers
total_customers = customers_table['Customer ID'].nunique()
print(f"Total number of customers: {total_customers}")

# 2. Distribution of customers by segments
segment_distribution = customers_table['Segment'].value_counts()
print("\nCustomer distribution by segments:")
print(segment_distribution)

# Bar chart for customer segments with enhancements
import matplotlib.pyplot as plt
import seaborn as sns  # Import seaborn

# Apply the seaborn style before creating the plot
sns.set_theme(style="darkgrid")  # Use seaborn.set_theme to set the style

ax = segment_distribution.plot(kind='bar', color=sns.color_palette("viridis", n_colors=segment_distribution.shape[0]), figsize=(8, 5))

# Adding title and axis labels
plt.title('Customer Distribution by Segment', fontsize=14, fontweight='bold')
plt.xlabel('Segment', fontsize=12)
plt.ylabel('Number of Customers', fontsize=12)

# Adding numbers above the bars
for i, v in enumerate(segment_distribution):
    plt.text(i, v + 1, str(v), ha='center', fontsize=10)

plt.xticks(rotation=0)  # Keep segment labels horizontal
plt.tight_layout()  # Adjust layout
plt.show()

#  Linking customers to orders
customer_orders = orders_table.groupby('Customer ID')['Order ID'].nunique().reset_index()
customer_orders.columns = ['Customer ID', 'Total Orders']
print(customer_orders.head())


# Calculate the average number of orders per customer
avg_orders_per_customer = customer_orders['Total Orders'].mean()
print(f"\nAverage number of orders per customer: {avg_orders_per_customer:.2f}")

# ربط العملاء مع الطلبات
customer_orders = orders_table.merge(customers_table, on='Customer ID', how='inner')

# Get the 'postal_code' for each 'Customer ID' to link with regions_table
# Instead of trying to get 'postal_code' from customer_orders, get it from the original 'file' DataFrame
customer_postal_codes = file[['Customer ID', 'postal_code']].drop_duplicates().groupby('Customer ID')['postal_code'].first().reset_index()

# تلخيص الأداء العام لكل عميل
customer_performance = customer_orders.groupby('Customer ID').agg({
    'Order ID': 'nunique',  # عدد الطلبات الفريدة لكل عميل
}).reset_index()
customer_performance.rename(columns={'Order ID': 'Total Orders'}, inplace=True)

# Merge with customer_postal_codes to add 'postal_code'
customer_performance = customer_performance.merge(customer_postal_codes, on='Customer ID', how='left')

# Merge with location_table to get 'Region' based on 'postal_code', changed regions_table to location_table
customer_performance = customer_performance.merge(location_table[['postal_code', 'Region']], on='postal_code', how='left')


# حساب الأداء المالي لكل عميل من جدول الطلبات مباشرة
customer_financial_performance = orders_table.groupby('Customer ID').agg({
    'Sales': 'sum',         # إجمالي المبيعات لكل عميل
    'Profit': 'sum',        # إجمالي الأرباح لكل عميل
    'Discount': 'sum',      # إجمالي الخصومات لكل عميل
}).reset_index()

# دمج الأداء المالي مع الأداء العام
final_customer_performance = customer_performance.merge(customer_financial_performance, on='Customer ID', how='inner')

# إضافة معلومات القطاع (Segment)
final_customer_performance = final_customer_performance.merge(customers_table[['Customer ID', 'Segment']], on='Customer ID', how='inner')

# عرض البيانات النهائية
print(final_customer_performance.head())

#توزيع المبيعات حسب القطاعات
import matplotlib.pyplot as plt
import seaborn as sns

# Calculate total sales by segment
segment_sales = final_customer_performance.groupby('Segment')['Sales'].sum().reset_index()

# Set the style for the plot
sns.set_theme(style="whitegrid")  # Use a clean whitegrid style

# Create the bar plot with enhanced styling
plt.figure(figsize=(10, 6))  # Adjust figure size for better proportions
ax = sns.barplot(
    data=segment_sales,
    x='Segment',
    y='Sales',
    palette="viridis",  # Choose a visually appealing color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize the plot elements
plt.title(
    'Total Sales by Customer Segment',  # Add a clear and concise title
    fontsize=16,  # Adjust font size for emphasis
    fontweight='bold',  # Make the title bold
)
plt.xlabel(
    'Customer Segment',  # Use a descriptive x-axis label
    fontsize=14,  # Adjust font size for readability
)
plt.ylabel(
    'Total Sales',  # Use a descriptive y-axis label
    fontsize=14,  # Adjust font size for readability
)

# Add data labels to the bars
for p in ax.patches:
    ax.annotate(
        f'{p.get_height():.0f}',  # Format the data label (e.g., remove decimals)
        (p.get_x() + p.get_width() / 2., p.get_height()),  # Position the label
        ha='center',  # Horizontal alignment
        va='center',  # Vertical alignment
        xytext=(0, 10),  # Adjust label offset
        textcoords='offset points',  # Use offset points for positioning
        fontsize=12,  # Adjust font size
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Calculate total sales, profit, and average discount by segment
segment_performance = final_customer_performance.groupby('Segment').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Discount=('Discount', 'mean')  # Calculate average discount
).reset_index()

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the combo chart
fig, ax1 = plt.subplots(figsize=(12, 6))

# Bar chart for Total Sales and Total Profit
bar_width = 0.35  # Adjust bar width and line position # This was the problematic comment, changed to regular comment
x_pos = np.arange(len(segment_performance['Segment']))

ax1.bar(x_pos, segment_performance['Total_Sales'], width=bar_width, label='Total Sales', color='skyblue')
ax1.bar(x_pos + bar_width, segment_performance['Total_Profit'], width=bar_width, label='Total Profit', color='lightcoral')

# Customize primary y-axis (for Sales and Profit)
ax1.set_ylabel('Amount', fontsize=14)
ax1.set_xlabel('Customer Segment', fontsize=14)
ax1.set_title('Sales, Profit, and Discount by Customer Segment', fontsize=16, fontweight='bold')
ax1.set_xticks(x_pos + bar_width / 2)
ax1.set_xticklabels(segment_performance['Segment'], rotation=45, ha='right', fontsize=12)
ax1.legend(loc='upper left', fontsize=12)

# Secondary y-axis for Average Discount (line chart)
ax2 = ax1.twinx()
ax2.plot(x_pos + bar_width / 2, segment_performance['Average_Discount'], marker='o', color='darkgreen', label='Average Discount')
ax2.set_ylabel('Average Discount', fontsize=14)
ax2.legend(loc='upper right', fontsize=12)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

#أفضل 10 عملاء من حيث المبيعات
import matplotlib.pyplot as plt
import seaborn as sns

top_customers = final_customer_performance.nlargest(10, 'Sales')

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the bar plot with enhancements
plt.figure(figsize=(12, 6))  # Adjust figure size for better readability
ax = sns.barplot(
    data=top_customers,
    x='Customer ID',
    y='Sales',
    palette='viridis',  # Use a visually appealing color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    'Top 10 Customers by Sales',
    fontsize=16,
    fontweight='bold',
)
plt.xlabel(
    'Customer ID',
    fontsize=14,
)
plt.ylabel(
    'Total Sales',
    fontsize=14,
)
plt.xticks(rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels for better readability

# Add data labels to the bars
for p in ax.patches:
    ax.annotate(
        f'{p.get_height():.0f}',
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha='center',
        va='center',
        xytext=(0, 10),
        textcoords='offset points',
        fontsize=10,
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

# Get the top 10 customers by sales
top_customers = final_customer_performance.nlargest(10, 'Sales')['Customer ID'].tolist()

# Link customer IDs with their cities and states using orders_table and regions_table
# Instead of using 'postal_code', use 'LOCATION KEY' which should be present in orders_table
top_customer_locations = orders_table[orders_table['Customer ID'].isin(top_customers)][['Customer ID', 'LOCATION KEY']].drop_duplicates()
top_customer_locations = top_customer_locations.merge(location_table[['LOCATION KEY', 'City', 'State']], on='LOCATION KEY', how='left')  # Use location_table instead of LOCATION_table and regions_table

# Group by Customer ID and get the city and state for each
top_customer_locations = top_customer_locations.groupby('Customer ID')[['City', 'State']].first().reset_index()

# Merge with customers_table to add 'Segment'
top_customer_locations = top_customer_locations.merge(customers_table[['Customer ID', 'Segment']], on='Customer ID', how='left')

# Print the results
print("City, State, and Segment of Top 10 Customers by Sales:")
print(top_customer_locations)

"""## ***Product Analysis ***"""

#دمج البيانات
import pandas as pd

# تحميل البيانات
# Assuming 'orders_table' and 'products_table' are your DataFrames
# If you saved them as CSV files, load them like this:
# orders = pd.read_csv("orders_table.csv")
# products = pd.read_csv("products_table.csv")

orders = orders_table # Assign the orders_table DataFrame to the variable 'orders'
products = products_table # Assign the products_table DataFrame to the variable 'products'

# ربط البيانات باستخدام Product Key
merged_data = orders.merge(products, on="PRODUCT KEY", how="left") # Changed 'Product Key' to 'PRODUCT KEY' to match column name

# عرض أول 5 صفوف بعد الدمج للتأكد
merged_data.head()

"""##** Product Analysis**"""

import pandas as pd

# Assuming 'products_table' is your DataFrame
# If you loaded it from a CSV, use: products_table = pd.read_csv("products_table.csv")

# 1. Total number of products
total_products = products_table.shape[0]  # shape[0] gives the number of rows

# 2. Number of categories
num_categories = products_table['Category'].nunique()

# 3. Number of sub-categories
num_sub_categories = products_table['Sub-Category'].nunique()

# Print the results
print("Total Products:", total_products)
print("Number of Categories:", num_categories)
print("Number of Sub-Categories:", num_sub_categories)

# To see the unique values in Category and Sub-Category columns:
print("\nUnique Categories:", products_table['Category'].unique())
print("\nUnique Sub-Categories:", products_table['Sub-Category'].unique())

orders_table['Product Name'] = orders_table['Product Name'].astype(str)
missing_products = orders_table['Product Name'].isnull().sum()
print(f"عدد القيم المفقودة في Product Name: {missing_products}")
orders_table['Product Name'] = orders_table['Product Name'].str.strip()
duplicate_products = orders_table['Product Name'].duplicated().sum()
print(f"عدد المنتجات المكررة: {duplicate_products}")
print(f"عدد المنتجات الفريدة: {orders_table['Product Name'].nunique()}")
merged_data = orders_table.merge(products_table, on='PRODUCT KEY', how='left') # Corrected variable names and column name
print(merged_data.columns)
# Access the 'Product Name' column from the correct DataFrame (products_table)
# after the merge using the '_y' suffix (since 'how' is 'left')
missing_products = merged_data['Product Name_y'].isnull().sum()
print(f"عدد المنتجات غير المرتبطة بمفتاح في product_table: {missing_products}")

top_10_summary = (
    merged_data.groupby('Product Name_y')
    .agg({'Sales': 'sum', 'Discount': 'mean', 'Profit': 'sum'})
    .nlargest(10, 'Sales')
    .reset_index()
)
import pandas as pd

# تنسيق الجدول بشكل أفضل
from IPython.display import display

display(top_10_summary)

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'top_10_summary' is already calculated

# Set the style for the plot
sns.set_theme(style="whitegrid")  # Use a clean whitegrid style

# Create the bar plot with enhancements
plt.figure(figsize=(12, 6))  # Adjust figure size for better readability
ax = sns.barplot(
    data=top_10_summary,
    x='Sales',
    y='Product Name_y',  # Changed 'Product Name_x' to 'Product Name_y'
    palette='viridis',  # Use a visually appealing color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    'Top 10 Products by Sales',
    fontsize=16,
    fontweight='bold',
)
plt.xlabel(
    'Total Sales',
    fontsize=14,
)
plt.ylabel(
    'Product Name',
    fontsize=14,
)

# Add data labels to the bars
for p in ax.patches:
    ax.annotate(
        f'{p.get_width():.0f}',  # Format the data label (e.g., remove decimals)
        (p.get_width(), p.get_y() + p.get_height() / 2.),  # Position the label
        ha='left',  # Horizontal alignment
        va='center',  # Vertical alignment
        xytext=(5, 0),  # Adjust label offset
        textcoords='offset points',  # Use offset points for positioning
        fontsize=10,  # Adjust font size
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate total sales per product
product_sales = merged_data.groupby('Product Name_y')['Sales'].sum().reset_index()

# Sort products by sales in ascending order
bottom_10_products = product_sales.nsmallest(10, 'Sales')

# Create a bar chart with enhancements
plt.figure(figsize=(12, 6))  # Adjust figure size for better readability
ax = sns.barplot(
    data=bottom_10_products,
    x='Sales',
    y='Product Name_y',
    palette='viridis',  # Use a visually appealing color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    'Bottom 10 Selling Products',  # Title in English
    fontsize=16,
    fontweight='bold',
)
plt.xlabel(
    'Total Sales',  # X-axis label in English
    fontsize=14,
)
plt.ylabel(
    'Product Name',  # Y-axis label in English
    fontsize=14,
)

# Add data labels to the bars for better readability
for p in ax.patches:
    ax.annotate(
        f'{p.get_width():.0f}',  # Format the data label (e.g., remove decimals)
        (p.get_width(), p.get_y() + p.get_height() / 2.),  # Position the label
        ha='left',  # Horizontal alignment
        va='center',  # Vertical alignment
        xytext=(5, 0),  # Adjust label offset
        textcoords='offset points',  # Use offset points for positioning
        fontsize=10,  # Adjust font size
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

"""##  **Impact discount on profit for products**

"""

# Change the groupby column to 'Product Name_x' or 'Product Name_y',
# depending on the actual column name in 'merged_data'.
product_discount_analysis = merged_data.groupby("Product Name_x").agg({ # Changed to 'Product Name_x'
    "Sales": "sum",
    "Profit": "sum",
    "Discount": "mean" # متوسط الخصم لكل منتج
}).reset_index()

# رسم العلاقة بين الخصم والمبيعات مع تحسينات
plt.figure(figsize=(12, 8))  # Increased figure size for better readability
sns.scatterplot(
    data=product_discount_analysis,
    x="Discount",
    y="Sales",
    hue="Profit",  # Add color based on profit
    size="Profit",  # Vary marker size based on profit
    sizes=(20, 200),  # Set size range for markers
    palette="viridis",  # Use a visually appealing color palette
    alpha=0.7,  # Add transparency for better visibility
)
plt.title("Impact of Discount on Sales", fontsize=16, fontweight='bold')  # Enhanced title
plt.xlabel("Average Discount", fontsize=14)  # Increased label font size
plt.ylabel("Total Sales", fontsize=14)  # Increased label font size
plt.grid(True, linestyle='--', alpha=0.7)  # Lighter grid for better readability
sns.despine()  # Remove top and right spines for a cleaner look
plt.tight_layout()  # Adjust layout for better spacing
plt.show()

"""## (good product)تحليل المنتجات ذات أعلى مبيعات وأقل خصم"""

import pandas as pd

# تجميع البيانات لكل منتج
# Use 'PRODUCT KEY' instead of 'Product ID' for grouping as it's the primary key for products now
product_analysis = orders.groupby("PRODUCT KEY").agg({
    "Sales": "sum",      # إجمالي المبيعات لكل منتج
    "Discount": "mean"   # متوسط الخصم لكل منتج
}).reset_index()

# دمج البيانات مع جدول products_table للحصول على Category و Sub-Category
product_analysis = pd.merge(product_analysis, products_table[['PRODUCT KEY', 'Category', 'Sub-Category']], on='PRODUCT KEY', how='left') # Assuming 'products_table' is available

# ترتيب المنتجات حسب أعلى مبيعات وأقل خصم
best_products = product_analysis.sort_values(by=["Sales", "Discount"], ascending=[False, True])

# عرض أفضل 10 منتجات تحقق مبيعات عالية بخصم منخفض مع Category و Sub-Category
best_products.head(10)

"""## (good) تحليل المنتجات التي تحقق أعلى ربحية مع أقل خصم"""

#بعض المنتجات قد تحقق مبيعات جيدة ولكن بأرباح منخفضة بسبب الخصومات الكبيرة.

profit_analysis = orders.groupby("PRODUCT KEY").agg({ # Changed "Product_ID" to "PRODUCT KEY"
    "Sales": "sum",
    "Profit": "sum",
    "Discount": "mean"
}).reset_index()

# ترتيب المنتجات حسب أعلى ربح وأقل خصم
best_profit_products = profit_analysis.sort_values(by=["Profit", "Discount"], ascending=[False, True])

# عرض أفضل 10 منتجات
best_profit_products.head(10)

"""## **تحليل المنتجات ذات المبيعات الجيدة ولكن بأرباح منخفضة بسبب الخصومات**إعادة تسعير"""

# حساب إجمالي المبيعات والأرباح ومتوسط الخصم لكل منتج
# Change 'Product_ID' to 'PRODUCT KEY' as it's the primary key for products now
low_profit_analysis = orders.groupby("PRODUCT KEY").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Discount": "mean"
}).reset_index()

# تصنيف المنتجات ذات المبيعات العالية والأرباح المنخفضة
low_profit_analysis = low_profit_analysis[(low_profit_analysis["Sales"] > low_profit_analysis["Sales"].median()) &
                                          (low_profit_analysis["Profit"] < low_profit_analysis["Profit"].median())]

# ترتيب المنتجات حسب أعلى مبيعات وأقل أرباح
low_profit_analysis = low_profit_analysis.sort_values(by=["Sales", "Profit"], ascending=[False, True])

# عرض أفضل 10 منتجات في هذه الفئة
low_profit_analysis.head(10)

import seaborn as sns
import matplotlib.pyplot as plt

# Set the style for the plot
sns.set_theme(style="whitegrid")  # Use a clean whitegrid style

plt.figure(figsize=(12, 8))  # Increase figure size for better readability

# Create the scatter plot with enhancements
scatter = sns.scatterplot(
    data=low_profit_analysis,
    x="Discount",
    y="Profit",
    size="Sales",
    hue="Sales",
    palette="coolwarm",  # Use a diverging color palette for better contrast
    sizes=(20, 300),  # Adjust size range for better visibility
    alpha=0.7,  # Add transparency for better readability when points overlap
    edgecolor="black",  # Add edge color to the markers
    linewidth=1.2,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    "Effect of Discount on Profit",  # English title
    fontsize=18,  # Adjust font size for emphasis
    fontweight='bold',  # Make the title bold
)
plt.xlabel(
    "Average Discount",  # English x-axis label
    fontsize=14,  # Adjust font size for readability
)
plt.ylabel(
    "Total Profit",  # English y-axis label
    fontsize=14,  # Adjust font size for readability
)
plt.xticks(fontsize=12)  # Adjust x-axis tick font size
plt.yticks(fontsize=12)  # Adjust y-axis tick font size

# Get the legend handles and labels directly from the Axes object
handles, labels = scatter.get_legend_handles_labels()

# Add a legend for size and color
legend_size = plt.legend(
    handles,
    labels,
    title="Sales",
    loc="upper right",
    bbox_to_anchor=(1.15, 1),  # Adjust legend position outside the plot
    fontsize=12,
    title_fontsize=14,
)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

"""## 📊 تحليل أداء المنتجات عبر الزمن لتحديد المواسم القوية والضعيفة"""

product_sales_trend = orders.groupby(["PRODUCT KEY", "Year", "Month","Quarter"])["Sales"].sum().reset_index()
print(product_sales_trend.head())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Assuming you have already calculated top_months and low_months

# Calculate average sales for each month
monthly_avg_sales = product_sales_trend.groupby('Month')['Sales'].mean().reset_index()

# Define a threshold for low sales (you may adjust this based on your data)
low_sales_threshold = monthly_avg_sales['Sales'].quantile(0.25)  # Using 25th percentile as threshold

# Identify low-sale months
low_months = monthly_avg_sales[monthly_avg_sales['Sales'] < low_sales_threshold]

# Calculate total sales for each month
monthly_sales = product_sales_trend.groupby('Month')['Sales'].sum().reset_index()

# Create a column to mark low-sale months
monthly_sales['Low_Month'] = False
low_months_list = low_months['Month'].tolist()  # Get list of low-sale months
monthly_sales.loc[monthly_sales['Month'].isin(low_months_list), 'Low_Month'] = True  # Mark low-sale months

# Plot the bar chart with highlighting for low-sale months
plt.figure(figsize=(10, 6))
ax = sns.barplot(data=monthly_sales, x='Month', y='Sales',
                 palette=['red' if is_low_month else 'steelblue' for is_low_month in monthly_sales['Low_Month']])
plt.title('Monthly Sales')
plt.xlabel('Month')
plt.ylabel('Total Sales')

# Add sales values above each bar using ax.text
for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                 ha='center', va='center', xytext=(0, 10), textcoords='offset points', fontsize=10)

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. دمج جدول المنتجات مع جدول الطلبات للحصول على اسم المنتج
merged_data = pd.merge(orders_table, products_table, on="PRODUCT KEY", how="left")

# 2. حساب إجمالي المبيعات لكل منتج شهريًا
# Check if 'Product Name' column exists in merged_data
if 'Product Name_x' in merged_data.columns:
    product_sales_trend = merged_data.groupby(['Month', 'Product Name_x'])['Sales'].sum().reset_index()
else:
    # If not found, print the available columns for debugging
    print(f"Available columns in merged_data: {merged_data.columns}")
    # Optionally, try a different column name if you suspect a mismatch
    # For example, if the column is named 'product_name', replace 'Product Name' with 'product_name'
    # product_sales_trend = merged_data.groupby(['Month', 'product_name'])['Sales'].sum().reset_index()

# 3. تحديد المنتجات ذات الأداء المنخفض (تعديل العتبة حسب الحاجة)
low_sales_threshold = product_sales_trend.groupby('Product Name_x')['Sales'].sum().quantile(0.25)
low_sales_products = product_sales_trend.groupby('Product Name_x')['Sales'].sum().reset_index()
low_sales_products = low_sales_products[low_sales_products['Sales'] < low_sales_threshold]

# 4. تصفية بيانات اتجاه المبيعات للمنتجات ذات الأداء المنخفض فقط
low_perf_trend = product_sales_trend[product_sales_trend['Product Name_x'].isin(low_sales_products['Product Name_x'])]

# 5. رسم بيانات اتجاه المبيعات مع تحسينات للعرض
plt.figure(figsize=(14, 8))
sns.lineplot(data=low_perf_trend, x='Month', y='Sales', hue='Product Name_x', marker='o', palette='viridis')  # استخدام لوحة ألوان أفضل

plt.title('Sales Trend for Low Performing Products', fontsize=16, fontweight='bold')  # عنوان أكبر وأكثر وضوحًا
plt.xlabel('Month', fontsize=12)  # تسمية المحور X
plt.ylabel('Total Sales', fontsize=12)  # تسمية المحور Y
plt.xticks(range(1, 13), ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])  # أسماء الشهور
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=10)  # تحسين حجم الخط في الأسطورة
plt.grid(True, linestyle='--', alpha=0.7)  # شبكة أكثر نعومة
sns.despine()  # إزالة الحدود العلوية واليمنى للمخطط

plt.tight_layout()  # ضبط المسافات تلقائيًا
plt.show()

"""## **📊 تحليل الفئات (Category & Sub-Category) وتأثيرها على المبيع**ات"""

import pandas as pd

# Assuming you have already loaded orders_table and products_table

# Merge orders_table with products_table using 'PRODUCT KEY'
orders_with_category = pd.merge(orders_table, products_table[['PRODUCT KEY', 'Category']], on='PRODUCT KEY', how='left')

# Now, orders_with_category will have a new column 'Category'
# You can use this DataFrame for your analysis

# Example: Group by 'Category' and calculate total sales
category_sales = orders_with_category.groupby('Category')['Sales'].sum().reset_index()
category_sales = category_sales.sort_values(by='Sales', ascending=False)
print(category_sales)

merged_data = orders_table.merge(products_table, on='PRODUCT KEY', how='left')  # Changed 'Product Key' to 'PRODUCT KEY'
file['PRODUCT KEY'] = file['Product ID'].astype(str) + "_" + file['Product Name']
merged_data = orders_table.merge(products_table, on='PRODUCT KEY', how='left') # Changed 'Product Key' to 'PRODUCT KEY'

# ترتيب البيانات تنازليًا حسب المبيعات
sub_category_sales = sub_category_sales.sort_values(by='Sales', ascending=False)

# عرض النتائج
print(sub_category_sales.head(10))  # عرض أعلى 10 فئات فرعية من حيث المبيعات

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Assuming you have already loaded orders_table and products_table

# Calculate total sales per product and month
product_sales_trend = orders_table.groupby(['PRODUCT KEY', 'Month'])['Sales'].sum().reset_index()

# Merge product_sales_trend with products_table to get the 'Category' column
product_sales_trend = pd.merge(product_sales_trend, products_table[['PRODUCT KEY', 'Category']], on='PRODUCT KEY', how='left')

# Now, product_sales_trend will have the 'Category' column

# Set the style for the plot
sns.set_theme(style="whitegrid")

# Create the line plot with enhancements
plt.figure(figsize=(14, 7))  # Adjust figure size for better proportions
ax = sns.lineplot(
    data=product_sales_trend,
    x="Month",
    y="Sales",
    hue="Category",
    palette="viridis",  # Use a visually appealing color palette
    linewidth=2.5,  # Increase line width for better visibility
    marker='o',  # Add markers to the lines
    markersize=8,  # Adjust marker size
    style="Category",  # Use different line styles for each category
    dashes=True,  # Add dashes to the lines
)

# Customize plot elements
plt.title(
    'Sales Trend per Category Over Time',
    fontsize=16,
    fontweight='bold',
)
plt.xlabel(
    'Month',
    fontsize=14,
)
plt.ylabel(
    'Total Sales',
    fontsize=14,
)

# Set x-axis ticks to represent month names
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']  # Month names
plt.xticks(range(1, 13), months, rotation=45, ha='right', fontsize=12)

# Customize legend
plt.legend(title="Category", fontsize=12, title_fontsize=12)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

merged_data = orders_table.merge(products_table, on='PRODUCT KEY', how='left')  # Changed 'Product Key' to 'PRODUCT KEY'
file['PRODUCT KEY'] = file['Product ID'].astype(str) + "_" + file['Product Name']
merged_data = orders_table.merge(products_table, on='PRODUCT KEY', how='left') # Changed 'Product Key' to 'PRODUCT KEY'

# ترتيب البيانات تنازليًا حسب المبيعات
sub_category_sales = sub_category_sales.sort_values(by='Sales', ascending=False)

# عرض النتائج
print(sub_category_sales.head(10))  # عرض أعلى 10 فئات فرعية من حيث المبيعات

plt.figure(figsize=(12,6))
sns.barplot(data=sub_category_sales, x='Sub-Category', y='Sales', palette='coolwarm')
plt.title('Total Sales by Sub-Category')
plt.xlabel('Sub-Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=90)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Merge orders_table with products_table to get 'Category'
orders_with_category = pd.merge(orders_table, products_table[['PRODUCT KEY', 'Category']], on='PRODUCT KEY', how='left')

# 2. Group by 'order_date' and 'Category', and calculate total sales
category_time_sales = orders_with_category.groupby(['order_date', 'Category'])['Sales'].sum().reset_index()

# 3. Create the line plot with enhancements
plt.figure(figsize=(16, 8))  # Adjust figure size for better readability
sns.set_theme(style="whitegrid")  # Use a clean whitegrid style
ax = sns.lineplot(
    data=category_time_sales,
    x='order_date',
    y='Sales',
    hue='Category',
    palette="viridis",  # Use a visually appealing color palette
    linewidth=2.5,  # Increase line width for better visibility
    marker='o',  # Add markers to the lines
    markersize=8,  # Adjust marker size
    style="Category",  # Use different line styles for each category
    dashes=True,  # Add dashes to the lines
)

# Customize plot elements
plt.title(
    'Sales Trend by Category Over Time',
    fontsize=18,
    fontweight='bold',
)
plt.xlabel(
    'Date',
    fontsize=14,
)
plt.ylabel(
    'Total Sales',
    fontsize=14,
)

# Customize x-axis ticks for better readability
plt.xticks(rotation=45, ha='right', fontsize=12)

# Customize legend
plt.legend(title="Category", fontsize=12, title_fontsize=12)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Merge orders_table with products_table to get 'Sub-Category'
orders_table = pd.merge(orders_table, products_table[['PRODUCT KEY', 'Sub-Category']], on='PRODUCT KEY', how='left')

# Calculate total sales and average discount for each sub-category
sub_category_discount = orders_table.groupby('Sub-Category').agg({'Sales': 'sum', 'Discount': 'mean'}).reset_index()

# Create the scatter plot with enhancements
plt.figure(figsize=(14, 8))  # Increased figure size
sns.set_theme(style="whitegrid")  # Use white background with grid

sns.scatterplot(
    data=sub_category_discount,
    x='Discount',
    y='Sales',
    hue='Sub-Category',
    size='Sales',
    sizes=(50, 500),  # Adjusted point sizes
    palette='viridis',  # Gradient color scheme
    edgecolor='black',  # Added black borders to points
    linewidth=1,  # Adjusted border thickness
    alpha=0.8  # Adjusted point transparency
)

# Enhancements to the plot's formatting
plt.title('Impact of Discount on Sales for Sub-Categories', fontsize=18, fontweight='bold')  # More prominent title
plt.xlabel('Average Discount', fontsize=14)  # X-axis label
plt.ylabel('Total Sales', fontsize=14)  # Y-axis label
plt.xticks(fontsize=12)  # Adjusted x-axis tick font size
plt.yticks(fontsize=12)  # Adjusted y-axis tick font size
plt.legend(fontsize=12, title='Sub-Category', title_fontsize=12)  # Enhanced legend
plt.grid(True, linestyle='--', alpha=0.7)  # Added grid with adjusted transparency

plt.tight_layout()  # Adjusted layout for better spacing
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Merge orders_table with products_table to get 'Category'
orders_with_category = pd.merge(orders_table, products_table[['PRODUCT KEY', 'Category']], on='PRODUCT KEY', how='left')

# Calculate total sales and average discount for each category
category_discount = orders_with_category.groupby('Category').agg({'Sales': 'sum', 'Discount': 'mean'}).reset_index()

# Create the scatter plot with enhancements
plt.figure(figsize=(14, 8))  # Increased figure size
sns.set_theme(style="whitegrid")  # Use white background with grid

sns.scatterplot(
    data=category_discount,
    x='Discount',
    y='Sales',
    hue='Category',
    size='Sales',
    sizes=(50, 500),  # Adjusted point sizes
    palette='viridis',  # Gradient color scheme
    edgecolor='black',  # Added black borders to points
    linewidth=1,  # Adjusted border thickness
    alpha=0.8  # Adjusted point transparency
)

# Enhancements to the plot's formatting
plt.title('Impact of Discount on Sales for Categories', fontsize=18, fontweight='bold')  # More prominent title
plt.xlabel('Average Discount', fontsize=14)  # X-axis label
plt.ylabel('Total Sales', fontsize=14)  # Y-axis label
plt.xticks(fontsize=12)  # Adjusted x-axis tick font size
plt.yticks(fontsize=12)  # Adjusted y-axis tick font size
plt.legend(fontsize=12, title='Category', title_fontsize=12)  # Enhanced legend
plt.grid(True, linestyle='--', alpha=0.7)  # Added grid with adjusted transparency

plt.tight_layout()  # Adjusted layout for better spacing
plt.show()

"""## **Location Analysis**"""

# Assuming 'file' contains your data
unique_cities = file['City'].nunique()
unique_states = file['State'].nunique()

# Print the results
print(f"Number of unique cities: {unique_cities}")
print(f"Number of unique states: {unique_states}")

# Assuming 'file' or 'location_table' contains your data
location_counts = file.groupby(['City', 'State'])['Identity_Key'].count().reset_index()
location_counts.rename(columns={'Identity_Key': 'Count'}, inplace=True)

# Print the results in a formatted way
print("Location Counts (City, State):")
for index, row in location_counts.iterrows():
    print(f"- {row['City']}, {row['State']}: {row['Count']}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Make sure pandas is imported

# Assuming 'orders_table' contains your data and has a 'Region' column
# If not, replace 'orders_table' with the correct DataFrame name
region_sales = orders_table.groupby('Region')['Sales'].sum().reset_index()  # Calculate region_sales

# Now you can continue with your plotting code:
# ضبط حجم المخطط
plt.figure(figsize=(12, 6))

# إنشاء مخطط شريطي مع ألوان متدرجة
ax = sns.barplot(data=region_sales, x='Region', y='Sales', palette='coolwarm', edgecolor='black')

# إضافة القيم فوق كل عمود
for p in ax.patches:
    ax.annotate(f'{p.get_height():,.0f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=11, fontweight='bold', color='black')

# تحسين التنسيقات
plt.title('Total Sales by Region', fontsize=14, fontweight='bold')
plt.xlabel('Region', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# عرض المخطط
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd  # Import pandas for data manipulation

# Merge orders_table with location_table to get 'City' column
# Assuming orders_table and location_table are defined elsewhere
orders_table = pd.merge(orders_table, location_table[['LOCATION KEY', 'City']], on='LOCATION KEY', how='left', suffixes=('', '_location'))  # Add suffixes to avoid duplicate column names
# Calculate total sales per city and select the top 20
# Assuming orders_table is defined and has 'City' and 'Sales' columns
city_sales = orders_table.groupby('City')['Sales'].sum().reset_index()
top_20_cities = city_sales.sort_values(by='Sales', ascending=False).head(20)


# Create a bar plot for the top 20 cities by sales with enhancements
# Assuming top_20_cities is defined
plt.figure(figsize=(14, 8))  # Adjust figure size for better readability
sns.set_theme(style="whitegrid")  # Use a white background with grid for a cleaner look
palette = sns.color_palette("viridis", n_colors=20)  # Use a gradient color palette

ax = sns.barplot(
    data=top_20_cities,
    x='City',
    y='Sales',
    palette=palette,  # Apply the color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    'Top 20 Cities by Total Sales',
    fontsize=18,  # Increase title font size
    fontweight='bold',  # Make title bold
)
plt.xlabel(
    'City',
    fontsize=14,  # Increase x-axis label font size
)
plt.ylabel(
    'Total Sales',
    fontsize=14,  # Increase y-axis label font size
)
plt.xticks(rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels for better readability

# Add data labels to the bars
for p in ax.patches:
    ax.annotate(
        f'{p.get_height():,.0f}',  # Format sales with thousands separator
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha='center',
        va='center',
        xytext=(0, 10),
        textcoords='offset points',
        fontsize=10,
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import pandas as pd

# دمج جدول الطلبات مع جدول المواقع بناءً على 'LOCATION KEY'
merged_data = orders_table.merge(location_table[['LOCATION KEY', 'Region']], on='LOCATION KEY', how='left')

# عرض أول 5 صفوف للتحقق
merged_data.head()

# تحويل order_date إلى datetime
merged_data['order_date'] = pd.to_datetime(merged_data['order_date'])
# تجميع المبيعات حسب التاريخ والمنطقة
region_time_sales = merged_data.groupby(['order_date', 'Region_y'])['Sales'].sum().reset_index()

# عرض أول 5 صفوف للتحقق
region_time_sales.head()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Assuming 'region_time_sales' is already defined

# If 'Region_y' is present instead of 'Region', rename it:
if 'Region_y' in region_time_sales.columns and 'Region_y' not in region_time_sales.columns:
    region_time_sales.rename(columns={'Region_y': 'Region'}, inplace=True)

# رسم مخطط يوضح اتجاه المبيعات لكل منطقة بمرور الوقت
plt.figure(figsize=(14, 8))

# Use a more visually appealing color palette
sns.lineplot(
    data=region_time_sales,
    x='order_date',
    y='Sales',
    hue='Region_y',
    marker='o',
    palette='viridis',  # Use a gradient color palette
    linewidth=2,  # Increase line width for better visibility
    markersize=8,  # Increase marker size
)

# تحسين التنسيق
plt.title('Sales Trend by Region Over Time', fontsize=16, fontweight='bold')
plt.xlabel('Date', fontsize=14)
plt.ylabel('Total Sales', fontsize=14)
plt.legend(title='Region_y', fontsize=12, title_fontsize=12)  # Enhance legend
plt.xticks(rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels and adjust font size
plt.yticks(fontsize=12)  # Adjust y-axis tick font size
plt.grid(True, linestyle='--', alpha=0.7)  # Lighter grid

# Add data labels to highlight specific points (optional)
# For example, to label the last data point for each region:
# for region in region_time_sales['Region'].unique():
#     last_data_point = region_time_sales[region_time_sales['Region'] == region].iloc[-1]
#     plt.text(last_data_point['order_date'], last_data_point['Sales'], region, ha='left', va='bottom', fontsize=10)

# Remove top and right spines for a cleaner look
sns.despine()

# Adjust layout for better spacing
plt.tight_layout()

# عرض المخطط
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Check if 'Region' column exists in orders_table
if 'Region' in orders_table.columns:
    print("Region column is present in orders_table")

    # Proceed with analysis and visualization
    region_sales_analysis = orders_table.groupby('Region').agg({'Sales': 'sum', 'Discount': 'mean'}).reset_index()

    plt.figure(figsize=(12, 6))
    sns.scatterplot(
        data=region_sales_analysis,
        x='Discount',
        y='Sales',
        hue='Region',
        size='Sales',
        sizes=(50, 400),
        palette="viridis",
        alpha=0.7,
    )

    for i in range(len(region_sales_analysis)):
        plt.text(
            region_sales_analysis.loc[i, 'Discount'] + 0.01,
            region_sales_analysis.loc[i, 'Sales'],
            region_sales_analysis.loc[i, 'Region'],
            fontsize=10,
            ha='left',
            va='center',
        )

    plt.title('Impact of Discount on Sales by Region', fontsize=16, fontweight='bold')
    plt.xlabel('Average Discount', fontsize=12)
    plt.ylabel('Total Sales', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

else:
    print("Region column is missing in orders_table. Please add it first.")

# تحليل أفضل وأسوأ المناطق من حيث معدل النمو
# حساب إجمالي المبيعات لكل منطقة في كل سنة
merged_data['Year'] = merged_data['order_date'].dt.year # Changed 'Order Date' to 'order_date'

# Check if 'Region' column exists in merged_data
# If not, it might be named 'Region_x' or 'Region_y' due to the merge
region_column = 'Region'
if 'Region' not in merged_data.columns:
    if 'Region_x' in merged_data.columns:
        region_column = 'Region_x'
    elif 'Region_y' in merged_data.columns:
        region_column = 'Region_y'
    else:
        raise KeyError("Region column not found in merged_data")

# Use the correct region column name for grouping:
region_yearly_sales = merged_data.groupby([region_column, 'Year'])['Sales'].sum().reset_index()

# حساب معدل النمو السنوي لكل منطقة
region_yearly_sales['Sales Growth'] = region_yearly_sales.groupby(region_column)['Sales'].pct_change() * 100 # Use region_column here as well

# ترتيب المناطق بناءً على معدل النمو الأخير
growth_summary = region_yearly_sales.dropna().groupby(region_column)['Sales Growth'].last().reset_index() # Use region_column here as well
growth_summary = growth_summary.sort_values(by='Sales Growth', ascending=False)

# رسم المخطط
plt.figure(figsize=(12,6))
sns.barplot(data=growth_summary, x='Sales Growth', y=region_column, palette='coolwarm', edgecolor='black') # Use region_column here as well

# تحسين التنسيقات
plt.title('Annual Sales Growth by Region', fontsize=14, fontweight='bold')
plt.xlabel('Sales Growth (%)', fontsize=12)
plt.ylabel('Region', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)

plt.show()

"""## **Ship Mode Analysis**"""

# Assuming 'orders_table' or 'file' contains your data
ship_mode_counts = orders_table['Ship_Mode'].value_counts()

# Print the results in a formatted way
print("Ship Mode Counts:")
for ship_mode, count in ship_mode_counts.items():
    print(f"- {ship_mode}: {count}")

import matplotlib.pyplot as plt
import seaborn as sns

#1️⃣ تحليل نسبة استخدام كل "Ship Mode" 🚢
# حساب عدد الطلبات لكل وسيلة شحن
ship_mode_counts = merged_data['Ship_Mode'].value_counts().reset_index() # Changed 'Ship Mode' to 'Ship_Mode'
ship_mode_counts.columns = ['Ship Mode', 'Order Count'] # Changed 'Ship_Mode' to 'Ship Mode' in column name

# تحديد ألوان مميزة
colors = sns.color_palette('Set2')  # Or any other palette you like

# إبراز قطاع معين (مثال: Standard Class)
explode = [0, 0.1, 0, 0]  # Explode the second slice (Standard Class)

# رسم المخطط الدائري مع التحسينات
plt.figure(figsize=(8, 6))
plt.pie(
    ship_mode_counts['Order Count'],
    labels=ship_mode_counts['Ship Mode'],
    autopct='%1.1f%%',
    colors=colors,
    startangle=90,
    explode=explode,
    shadow=True,
    textprops={'fontsize': 12},  # Increase font size of labels
    wedgeprops={'edgecolor': 'black', 'linewidth': 1},  # Add black border to slices
)

# تحسين التنسيقات
plt.title('Distribution of Ship Mode Usage', fontsize=16, fontweight='bold')
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.

plt.show()

# تأثير "Ship Mode" على المبيعات
# تجميع المبيعات حسب Ship Mode
ship_mode_sales = merged_data.groupby('Ship_Mode')['Sales'].sum().reset_index()
ship_mode_sales = ship_mode_sales.sort_values(by='Sales', ascending=False)

# رسم المخطط مع تحسينات
plt.figure(figsize=(10, 6))  # حجم الرسم
sns.barplot(
    data=ship_mode_sales,
    x='Ship_Mode',
    y='Sales',
    palette='Blues_r',  # نظام ألوان احترافي
    edgecolor='black',  # حدود سوداء للخطوط
    linewidth=1.2,  # عرض خط الحدود
)

# تحسين التنسيقات
plt.title(
    'Total Sales by Ship Mode',  # عنوان أوضح
    fontsize=16,
    fontweight='bold',
)
plt.xlabel(
    'Ship Mode',
    fontsize=14,
)
plt.ylabel(
    'Total Sales',
    fontsize=14,
)

# إضافة قيم المبيعات أعلى كل خط
for index, value in enumerate(ship_mode_sales['Sales']):
    plt.text(
        index,
        value,
        f'{value:,.0f}',  # عرض القيم بفاصلات الآلاف
        ha='center',
        va='bottom',
        fontsize=12,
    )

plt.grid(axis='y', linestyle='--', alpha=0.7)  # شبكة خلفية خفيفة
sns.despine()  # إزالة الحدود العلوية واليمنى

plt.tight_layout()  # تحسين المسافات
plt.show()

# رسم مخطط يوضح العلاقة بين مدة الشحن ووسيلة الشحن مع تحسينات احترافية
plt.figure(figsize=(10, 5))  # تغيير حجم المخطط (اختياري)

# استخدام sns.boxplot مع تحسينات:
sns.boxplot(
    data=merged_data,
    x='Ship_Mode',  # تصحيح اسم العمود
    y='Shipping Duration',
    palette='coolwarm',  # نظام ألوان جذاب
    linewidth=2,  # زيادة سمك خطوط الصندوق
    fliersize=5,  # تغيير حجم النقاط الخارجية
    showmeans=True, # إظهار متوسطات القيم
    meanprops={"marker":"o",
               "markerfacecolor":"white",
               "markeredgecolor":"black",
              "markersize":"10"} # تخصيص شكل و حجم علامة المتوسط
)

# تحسين التنسيقات:
plt.title('Delivery Time by Ship Mode', fontsize=16, fontweight='bold')  # زيادة حجم الخط وجعله غامقًا
plt.xlabel('Ship Mode', fontsize=14)  # زيادة حجم الخط
plt.ylabel('Shipping Duration (Days)', fontsize=14)  # زيادة حجم الخط
plt.xticks(rotation=45, ha='right')  # تدوير تسميات المحور X وتعديل المحاذاة (اختياري)
plt.grid(axis='y', linestyle='--', alpha=0.7)  # شبكة خلفية أكثر وضوحًا

sns.despine()  # إزالة الحدود العلوية واليمنى للمخطط

plt.tight_layout()  # ضبط المسافات تلقائيًا
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Analyzing the impact of shipping mode on sales and profit

# Group data by Ship Mode and calculate total sales and profit
ship_analysis = merged_data.groupby('Ship_Mode').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()

# Reshape data into long format for easier plotting using melt
# Corrected the column name in id_vars to 'Ship_Mode' to match the column name in 'ship_analysis'
ship_analysis_melted = ship_analysis.melt(id_vars='Ship_Mode', var_name='Metric', value_name='Value')

# Create the bar plot with enhancements
plt.figure(figsize=(10, 6))  # Larger size for better display
sns.barplot(data=ship_analysis_melted, x='Ship_Mode', y='Value', hue='Metric', palette='viridis')  # Professional color scheme

# Improve plot aesthetics
plt.title('Impact of Ship Mode on Sales & Profit', fontsize=16, fontweight='bold')  # Clear title
plt.xlabel('Ship Mode', fontsize=14)  # X-axis label
plt.ylabel('Total Value', fontsize=14)  # Y-axis label
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
plt.legend(title='Metric', fontsize=12)  # Legend title and font size

# Add value labels above the bars
for p in plt.gca().patches:
    plt.gca().text(p.get_x() + p.get_width() / 2., p.get_height(), f'{p.get_height():,.0f}',
                 ha='center', va='bottom', fontsize=10)

plt.tight_layout()  # Adjust spacing
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Add a subtle background grid
sns.despine()  # Remove top and right spines for a cleaner look

plt.show()

# تحليل تاخير التوصيل
import numpy as np

# Assuming 'Shipping Duration' is your actual column name, and you want to check if shipping took more than 3 days
merged_data['Delivery Status'] = np.where(merged_data['Shipping Duration'] <= 3, 'On-Time', 'Delayed')  # Using Shipping Duration directly

# حساب نسبة الشحنات المتأخرة والمبكرة لكل وسيلة شحن
delivery_analysis = merged_data.groupby(['Ship_Mode', 'Delivery Status']).size().unstack().fillna(0)

# حساب النسب المئوية لكل وسيلة شحن
delivery_analysis_percentage = delivery_analysis.div(delivery_analysis.sum(axis=1), axis=0) * 100

# رسم المخطط البياني
plt.figure(figsize=(10,5))
delivery_analysis_percentage.plot(kind='bar', stacked=True, colormap='coolwarm', figsize=(10,5))

# تحسين العرض
plt.title('On-time vs. Delayed Shipments by Ship Mode', fontsize=14, fontweight='bold')
plt.xlabel('Ship Mode', fontsize=12)
plt.ylabel('Percentage (%)', fontsize=12)
plt.legend(title='Delivery Status')
plt.xticks(rotation=15)

plt.show()

# تحديد العملاء الذين قاموا بأكثر من عملية شراءl -loyalty analysis
customer_orders = merged_data.groupby('Customer ID')['Order ID'].nunique().reset_index()
customer_orders.columns = ['Customer ID', 'Total Orders']

# ضم بيانات العملاء مع بيانات التوصيل
customer_data = merged_data.merge(customer_orders, on='Customer ID', how='left')

# تصنيف العملاء إلى "تعرضوا لتأخير" أو "لم يتعرضوا لتأخير"
customer_data['Delayed Shipment'] = np.where(customer_data['Delivery Status'] == 'Delayed', 1, 0)

# حساب معدل تكرار الشراء للعملاء المتأثرين بالتأخير وغير المتأثرين
loyalty_analysis = customer_data.groupby('Delayed Shipment')['Total Orders'].mean()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Assuming you have already calculated 'loyalty_analysis'

# Create the bar plot with enhancements
plt.figure(figsize=(10, 6))  # Increased figure size for better readability
ax = sns.barplot(
    x=loyalty_analysis.index,
    y=loyalty_analysis.values,
    palette="coolwarm",  # Use a visually appealing color palette
    edgecolor=".2",  # Add edge color to the bars
    linewidth=1.5,  # Adjust linewidth for better visibility
)

# Customize plot elements
plt.title(
    "Impact of Delivery Delays on Customer Loyalty",
    fontsize=16,
    fontweight="bold",
)
plt.xlabel("Delivery Status", fontsize=14)
plt.ylabel("Average Orders per Customer", fontsize=14)
plt.xticks(ticks=[0, 1], labels=["On-Time Deliveries", "Delayed Deliveries"], fontsize=12)  # Increased font size for x-axis labels

# Add data labels to the bars
for p in ax.patches:
    ax.annotate(
        f"{p.get_height():.2f}",  # Format data label to two decimal places
        (p.get_x() + p.get_width() / 2., p.get_height()),
        ha="center",
        va="center",
        xytext=(0, 10),
        textcoords="offset points",
        fontsize=12,  # Increased font size for data labels
    )

# Remove top and right spines for a cleaner look
sns.despine()

# Add a subtle background grid
plt.grid(axis="y", linestyle="--", alpha=0.7)

# Adjust layout for better spacing
plt.tight_layout()

# Show the plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# 1. Merge data for shipping analysis
shipping_data = pd.merge(merged_data, orders_table[['Order ID', 'Region']], on="Order ID", how="left")

# 2. Select specific columns from location_table to avoid duplicates
shipping_data = pd.merge(shipping_data, location_table[['LOCATION KEY', 'Country', 'State']], on="LOCATION KEY", how="left")  # Only merge necessary columns


# 2. Create 'Delivery Status' and 'Delayed Shipment' if they don't exist
if 'Delivery Status' not in shipping_data.columns:
    shipping_data['Delivery Status'] = np.where(shipping_data['Shipping Duration'] <= 3, 'On-Time', 'Delayed')

if 'Delayed Shipment' not in shipping_data.columns:
    shipping_data['Delayed Shipment'] = np.where(shipping_data['Delivery Status'] == 'Delayed', 1, 0)

# 3. Aggregate data by region
region_shipping = shipping_data.groupby('Region').agg(
    Total_Orders=('Order ID', 'count'),
    Avg_Delivery_Days=('Shipping Duration', 'mean'),
    Delayed_Orders=('Delayed Shipment', 'sum')
).reset_index()

# 4. Calculate delay percentage
region_shipping['Delay_Percentage'] = (region_shipping['Delayed_Orders'] / region_shipping['Total_Orders']) * 100

# 5. Visualization: Average Delivery Duration by Region
plt.figure(figsize=(12, 6))  # Increased figure size
sns.barplot(data=region_shipping, x='Region', y='Avg_Delivery_Days', palette='coolwarm')
plt.title('Average Delivery Duration by Region', fontsize=16, fontweight='bold') # Enhanced title
plt.xlabel('Region', fontsize=14)  # Increased font size
plt.ylabel('Average Delivery Time (Days)', fontsize=14)  # Increased font size
plt.xticks(rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels with better alignment
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Added gridlines
sns.despine()  # Removed top and right spines
plt.tight_layout()  # Adjusted spacing

# Add data labels to the bars
for p in plt.gca().patches:
    plt.gca().text(p.get_x() + p.get_width() / 2., p.get_height(), f'{p.get_height():.1f}',
                 ha='center', va='bottom', fontsize=10)  # Display values on bars

plt.show()

# 6. Visualization: Delayed Shipments Percentage by Region
plt.figure(figsize=(12, 6))  # Increased figure size
sns.barplot(data=region_shipping, x='Region', y='Delay_Percentage', palette='Reds_r')
plt.title('Delayed Shipments Percentage by Region', fontsize=16, fontweight='bold')  # Enhanced title
plt.xlabel('Region', fontsize=14)  # Increased font size
plt.ylabel('Delay Percentage (%)', fontsize=14)  # Increased font size
plt.xticks(rotation=45, ha='right', fontsize=12)  # Rotate x-axis labels with better alignment
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Added gridlines
sns.despine()  # Removed top and right spines
plt.tight_layout()  # Adjusted spacing

# Add data labels to the bars
for p in plt.gca().patches:
    plt.gca().text(p.get_x() + p.get_width() / 2., p.get_height(), f'{p.get_height():.1f}%',
                 ha='center', va='bottom', fontsize=10) # Display percentages on bars

plt.show()